const metalKapaklar = [
    "LMD 302 GÜMÜŞ.png",
    "LMD 303 FIRÇAMETAL.png",
    "LMD 306 ALTIN DİŞBUDAK.png",
    "LMD 307 GÜMÜŞ DİŞBUDAK.png",
    "LMD 501 WHITEFLOWER.png",
    "LMD 502 NESVA.png",
    "LMD 504 SİYAH ASMA.png",
    "LMD 506 KAYRA.png",
    "LMD 508 BLACK FLOWER.png",
    "LMD 511 BEYAZ TAŞ.png",
    "LMD 512 KREM TAŞ.png",
    "LMD 512 KREM ÇAKILTAŞI.png",
    "LMD 513 SİYAH TAŞ.png",
    "LMD 514 KIRMIZI TAŞ.png",
    "LMD 516 BORDO TAŞ.png",
    "LMD 517 BEYAZ EFSUN.png",
    "LMD 518 SİYAH EFSUN.png",
    "LMD 521 SİYAH SILVERLINE.png",
    "LMD 522 BEYAZ ZIMPARA.png",
    "LMD 523 BAKIR ZIMPARA.png",
    "LMD 524 GÜMÜŞ ZIMPARA.png",
    "LMD 525 BRONZTAŞ.png",
    "LMD 527 DEKOR GOLD.png",
];

const ahşapKapaklar = [
    "LMD 201 SEDEF BEYAZ.jpg",
    "LMD 202 AKÇAAĞAÇ.jpg",
    "LMD 203 BEYAZ DİŞBUDAK.jpg",
    "LMD 204 KAYIN.jpg",
    "LMD 205 ARMUT.jpg",
    "LMD 206 İTALYAN CEVİZ.jpg",
    "LMD 207 KİRAZ.jpg",
    "LMD 209 RUSTİK.jpg",
    "LMD 211 MAUN.jpg",
    "LMD 212 KOYU CEVİZ.jpg",
    "LMD 213 WENGE.jpg",
    "LMD 214 YEŞİL ARMUT.jpg",
    "LMD 215 PUDRA MEŞE.jpg",
    "LMD 216 ESKİTME.jpg",
    "LMD 223 ABONOZ.jpg",
    "LMD 224 BAMBU.jpg",
    "LMD 226 KOYU KİRAZ.jpg",
    "LMD 229 BONSAI.jpg",
    "LMD 236 KOYU BAMBU.jpg",
    "LMD 241 BEYAZ COCO.jpg",
    "LMD 241 COCO.jpg",
    "LMD 245 BETULA.jpg",
    "LMD 258 LIGHT MEŞE.jpg",
    "LMD 259 DARK MEŞE.jpg",
    "LMD 261 BAL TEAK.jpg",
    "LMD 265 NATURAL AÇIK MEŞE.jpg",
    "LMD 266 NATURAL KOYU MEŞE.jpg",
    "LMD 267 NATURAL AÇIK ALPİ.jpg",
    "LMD 268 NATURAL KOYU ALPİ.jpg",
    "LMD 270 NATURAL LIGHT MAPLE.jpg",
    "LMD 272 NATURAL DARK OAK.jpg",
    "LMD 273 NATURAL ÖZEL ALPİ.jpg",
    "LMD 274 PATAYA.jpg",
    "LMD 275 PUKET.jpg",
    "LMD 276 TESTERE.jpg",
    "LMD 277NATUREL SONOMA MEŞE.jpg",
    "LMD 281 GRİ SONOMA MEŞE.jpg",
    "LMD 282 PREMİUM BEYAZ.jpg",
    "LMD 283 PREMİUM TEAK.jpg",
    "LMD 284 PREMİUM IHLAMUR.jpg",
    "LMD 285 PREMİUM KÖKNAR.jpg",
    "LMD 286 LMD PREMİUM LADİN.jpg",
    "LMD 290 ÖZEL COCO.jpg",
    "LMD 298 AÇIK NATURAL CEVİZ.png",
    "LMD 299 KOYU NATUREL CEVİZ.jpg",
];

const duzKapaklar = [
    "LMD 101 BEYAZ.jpg",
    "LMD 102 KREM.jpg",
    "LMD 103 SATEN BEYAZ.jpg",
    "LMD 105 PORTAKAL.jpg",
    "LMD 106 FISTIK YEŞİLİ.jpg",
    "LMD 109 KIRMIZI.jpg",
    "LMD 110 BORDO.jpg",
    "LMD 111 LİLA.jpg",
    "LMD 112 SİYAH.jpg",
    "LMD 113 PEMBE.jpg",
    "LMD 117 SATEN GRİ.jpg",
    "LMD 210 HUŞ.jpg",
];

const duzParlakKapaklar = [
    "LMD 401 PARLAK KIRMIZI.png",
    "LMD 402 PARLAK KREM.png",
    "LMD 407 PARLAK BORDO.png",
    "LMD 410 PARLAK SİYAH.png",
    "LMD 412 PARLAK MURDUM.png",
    "LMD 453 PARLAK KAHVE.png",
    "LMD 462 SEDEF BRONZ.png",
    "LMD 463 HARDAL SARI.png",
    "LMD 464 FUŞYA.png",
    "LMD 465 TURKUAZ MAVİ.png",
    "LMD 466 PARLAK PEMBE.png",
];

const highGlossKapaklar = [
    "LMD 601 BEYAZ ŞİMŞEK.png",
    "LMD 602 SİYAH ŞİMŞEK.png",
    "LMD 603 BEYAZ DALGA.png",
    "LMD 604 BEYAZ SARMAŞIK.png",
    "LMD 605 SİYAH SARMAŞIK.png",
    "LMD 606 KIRMIZI ŞİMŞEK.png",
    "LMD 607 ERİK DALGA.png",
    "LMD 608 ALTIN ŞİMŞEK.png",
    "LMD 610 SARI SALKIM.png",
    "LMD 611 METAL DALGA.png",
    "LMD 612 BEYAZ DAMLA.png",
    "LMD 614 KIRMIZI DAMLA.png",
    "LMD 616 VENÜS.png",
    "LMD 617 JÜPİTER.png",
    "LMD 618 NEPTÜN.png",
    "LMD 619 MARS.png",
    "LMD 620 SİYAH ZEBRA.png",
    "LMD 621 KARDELEN.png",
    "LMD 622 SİYAH MENEKŞE.png",
    "LMD 623 KIRMIZI MENEKŞE.png",
    "LMD 624 BEYAZ ORİON.png",
    "LMD 625 SİYAH ORİON.png",
    "LMD 626 KIRMIZI ORİON.png",
    "LMD 627 PARLAK BEY AZELİPS.png",
    "LMD 628 GRİELİPS.png",
    "LMD 629 BEYAZ GÜMÜŞ.png",
    "LMD 632 SİYAH SİHİRLİ NOKTA.png",
    "LMD 633 BEYAZ KÜRTÇÜK.png",
    "LMD 634 SİYAH KURTÇUK.png",
    "LMD 636 SİYAH YOSUN.png",
    "LMD 638 SİYAH S LINE.png",
    "LMD 641 BEYAZ SİHİRLİ DALGA.png",
    "LMD 642 SİYAH SİHİRLİ DALGA.png",
    "LMD 643 BEYAZ SİHİRLİ EK.png",
    "LMD 645 BEYAZ MELTEM.png",
    "LMD 646 SİYAH MELTEM.png",
    "LMD 647 BEYAZ EBRU.png",
    "LMD 648 SİYAH EBRU.png",
    "LMD 649 BEYAZ GÖK.png",
    "LMD 650 SİYAH GÖK.png",
    "LMD 651 KIRMIZI GÖK.png",
    "LMD 652 KIRMIZI SİHİRLİ DALGA.png",
    "LMD 653 BEYAZ GÜL.png",
    "LMD 654 SİYAH GÜL.png",
    "LMD 655 BORDO GÜL.png",
    "LMD 656 KREM MOZAİK.png",
    "LMD 657 SİYAH MOZAİK.png",
    "LMD 660 BEYAZ YAPRAK.png",
    "LMD 661 SİYAH YAPRAK.png",
];

const ozelKapaklar = [
    "LMD 429 PSEDEFLİLA.png",
    "LMD 438 PARLAK SEDEF KREM.png",
    "LMD 439 WHITE STAR.png",
    "LMD 440 PARLAK BLACK STAR.png",
    "LMD 456 GOLD METALİK.png",
    "LMD 457 BAL METALİK.png",
    "LMD 459 SİYAH EVREN.png",
    "LMD 460 LİLA EVREN.png",
    "LMD 461 BEJ METALİK.png",
];

const parlakAhşapKapaklar = [
    "LMD 403 PARLAK ABANOZ.png",
    "LMD 408 PARLAK MAKASSAR.png",
    "LMD 409 PARLAK ZEYTİN.png",
    "LMD 411 PARLAK CEVİZ.png",
    "LMD 414 PARLAK VENTURE.png",
    "LMD 415 PARLAK SİYAH CEVİZ.png",
    "LMD 416 PARLAK ELMA.png",
    "LMD 417 PARLAK AKÇAAĞAÇ.png",
    "LMD 418 PARLAK ALPİ.png",
    "LMD 420 PARLAK LİLYUM.png",
    "LMD 421 PARLAK GRİ MACASSAR.png",
    "LMD 425 PARLAK SANDALWOOD.png",
    "LMD 426 PARLAK BEYAZ DAMLA PVC.png",
    "LMD 427 PARLAK SİYAH DAMLA PVC.png",
    "LMD 428 PARLAK KIRMIZI DAMLA PVC.png",
    "LMD 430 PARLAK BEYAZ COCO.png",
    "LMD 431 PARLAK SEDEF BEJ.png",
    "LMD 432 PARLAK BLACKLINE.png",
    "LMD 433 PARLAK CAPPUCCINO.png",
    "LMD 434 PARLAK LIGHT BAMBU.png",
    "LMD 436 PARLAK YENİ SİYAH DAMLA.png",
    "LMD 437 PARLAK YENi KIRMIZI DAMLA.png",
    "LMD 441 BEYAZ NERGİS.png",
    "LMD 442 SİYAH NERGİS.png",
    "LMD 443 PARLAK ASYA.png",
    "LMD 444 PARLAK ZEYNEP.png",
    "LMD 445 PARLAK MOR NERGİS.png",
    "LMD 446 BEYAZ UZAY YOLU.png",
    "LMD 447 SİYAH UZAY YOLU.png",
    "LMD 448 SİYAH MERİDYEN.png",
    "LMD 449 CAPPUCCINO MERİDYEN.png",
    "LMD 450 BEYAZ SAÇAK.png",
    "LMD 451 SİYAH SAÇAK.png",
    "LMD 452 NOCE.png",
    "LMD 454 BEYAZ MERİDYEN.png",
    "LMD 455 PARLAK SONOMO MEŞE.png",
    "LMD 468 VOLKANİK TAŞ.png",
];

const softTouchKapaklar = [
    "LMB 712B KESTANE.png",
    "LMD 706 DARK CHERRY.png",
    "LMD 707 SOFT BEYAZ.png",
    "LMD 708 DOĞAL ANTİK.png",
    "LMD 709 NOCE MARİNO.png",
    "LMD 711B KARA AĞAÇ.png",
    "LMD 714 SOFT DOĞAL AKÇAAĞAÇ.png",
    "LMD 715 NOCE NİGRA.png",
    "LMD 715 SOFT NOCE NİGRA.png",
    "LMD 716 SOFT YATAY DOĞAL ABANOZ.png",
    "LMD 717 SOFT KREM.png",
    "LMD 718B MERBAU.png",
    "LMD 719 OKALİPTUS.png",
    "LMD 722 SOFT CAPPUCİNO.png",
    "LMD 726 SARAY CEVİZ.png",
    "LMD 726B SARAY CEVİZ.png",
    "LMD 728B SARAY MEŞE.png",
];

const kapakUzanti = "/kapaklar/";

export {
    ahşapKapaklar,
    duzKapaklar,
    duzParlakKapaklar,
    highGlossKapaklar,
    metalKapaklar,
    ozelKapaklar,
    parlakAhşapKapaklar,
    softTouchKapaklar,
    kapakUzanti,
};
