import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="tr"
            className="light"
        >
            <body className={`${inter.className} min-h-[100svh] antialiased`}>
                <Navbar />
                <main className="main-container">{children}</main>
            </body>
        </html>
    );
}

// bg-gradient-to-t from-[#171717] to-[#011222]
