import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/main-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="tr"
            className="light"
        >
            <body
                className={`${inter.className} min-h-screen antialiased bg-gradient-to-t from-[#171717] to-[#011222]`}
            >
                <Navigation />
                <main className="main-container">{children}</main>
            </body>
        </html>
    );
}
