export const primersizResimlerUzanti = "/kapilar/primersiz/";

export const primersizResimler = [
    "LMD 101 BEYAZ.jpg",
    "LMD 103 SATEN BEYAZ.jpg",
    "LMD 203 BEYAZ DİŞBUDAK.jpg",
    "LMD 206 İTALYAN CEVİZ.jpg",
    "LMD 212 KOYU CEVİZ.jpg",
    "LMD 213 WENGE.jpg",
    "LMD 224 BAMBU.jpg",
    "LMD 236 KOYU BAMBU.jpg",
    "LMD 241 BEYAZ COCO.jpg",
    "LMD 241 COCO.jpg",
    "LMD 261 BAL TEAK.jpg",
    "LMD 278 BEYAZ HUŞ.jpg",
    "LMD 279 OZİGO.jpg",
    "LMD 289 YABAN ELMA.jpg",
    "LMD 290 ÖZEL COCO.jpg",
    "LMD 291 AMERİKAN CEVİZ.jpg",
    "LMD 293 TANGANİKA.jpg",
    "LMD 298 AÇIK NATUREL CEVİZ.png",
    "LMD 299 KOYU NATUREL CEVİZ.jpg",
    "LMD 402 PARLAK KREM.jpg",
    "LMD 404P BEYAZ.jpg",
    "LMD 410 PARLAK SİYAH.jpg",
];
